---
title: "Oyster Metrics"
author: "Alexandra DiGiacomo"
date: "10/13/2020"
output: html_document
---

```{r, echo = FALSE}
# load packages

library(dplyr)
library(ggplot2)
library(raster)
library(sp)
library(rgdal)
library(spatialEco)
library(rasterVis)
library(rgl)
library(maptools)
library(gridExtra)
```

## Load Data
```{r , echo = FALSE}
# load data
parentfolder <- "C:/aed41/Projects/OysterMetrics/"

Natural2 <- raster(paste(parentfolder, "scratch/intermediateFiles/Natural2.tif", sep = ""))
Natural4 <- raster(paste(parentfolder, "scratch/intermediateFiles/Natural4.tif", sep = ""))

Natural2_slopAs <- raster(paste(parentfolder, "scratch/intermediateFiles/Natural2_slop.tif", sep = ""))
Natural4_slopAs <- raster(paste(parentfolder, "scratch/intermediateFiles/Natural4_slop.tif", sep = ""))
```

## Stack Rasters
```{r}
dsmSlopeStack <- stack(Natural2, resample(Natural4, Natural2), # upsample to be at same resolution for stack
                       Natural2_slopAs, resample(Natural4_slopAs, Natural2_slopAs))

```


## Post ArcGIS Processing: Sample Plots
```{r}
edgeSamples <- readShapePoly("C:/aed41/Projects/OysterMetrics/data/samplePlots/EdgePlots_Natural.shp")
crestSamples <- readShapePoly("C:/aed41/Projects/OysterMetrics/data/samplePlots/CrestPlots_Natural.shp")
```

Extract Raster Values at Sample Plots
```{r}
# edge 
meanEdgeSamples <- as.data.frame(extract(dsmSlopeStack, edgeSamples, fun = mean)) %>%
  mutate(area = "edge")
varEdgeSamples <- as.data.frame(extract(dsmSlopeStack, edgeSamples, fun = var)) %>%
  mutate(area = "edge")

# crest
meanCrestSamples <- as.data.frame(extract(dsmSlopeStack, crestSamples, fun = mean)) %>%
  mutate(area = "crest")
varCrestSamples <- as.data.frame(extract(dsmSlopeStack, crestSamples, fun = var)) %>%
  mutate(area = "crest")
```


Visualize Sample Means
```{r}
meanSamples <- rbind(meanEdgeSamples, meanCrestSamples)

# 2xGSD Elevation
p1 <- meanSamples %>%
  ggplot(aes(x = area, y = Natural2)) + geom_boxplot() + 
  theme_minimal() + ggtitle("Mean Elevation: Natural Reef", subtitle = 
                              "2 x GSD") + 
  ylab("Elevation")
  
# 4xGSD Elevation
p2 <- meanSamples %>%
  ggplot(aes(x = area, y = Natural4)) + geom_boxplot() + 
  theme_minimal() + ggtitle("Mean Elevation: Natural Reef", subtitle = 
                              "4 x GSD") +
  ylab("Elevation")
# 2xGSD Slope
p3 <- meanSamples %>%
  ggplot(aes(x = area, y = Natural2_slop)) + geom_boxplot() + 
  theme_minimal() + ggtitle("Mean Slope: Natural Reef", subtitle = 
                              "2 x GSD") + 
  ylab("Slope (degrees)")
# 4xGSD Slope
p4 <- meanSamples %>%
  ggplot(aes(x = area, y = Natural4_slop)) + geom_boxplot() + 
  theme_minimal() + ggtitle("Mean Slope: Natural Reef", subtitle = 
                              "4 x GSD") + 
  ylab("Slope (degrees)")

grid.arrange(p1, p2, p3, p4, ncol = 2)
```

Visualize Sample Variance
```{r}
varSamples <- rbind(varEdgeSamples, varCrestSamples)

# 2xGSD Elevation
p5 <- varSamples %>%
  ggplot(aes(x = area, y = Natural2)) + geom_boxplot() + 
  theme_minimal() + ggtitle("Elevation Variance: Natural Reef", subtitle = 
                              "2 x GSD") + 
  ylab("Variance in Elevation")
  
# 4xGSD Elevation
p6 <- varSamples %>%
  ggplot(aes(x = area, y = Natural4)) + geom_boxplot() + 
  theme_minimal() + ggtitle("Elevation Variance: Natural Reef", subtitle = 
                              "4 x GSD") +
  ylab("Variance in Elevation")
# 2xGSD Slope
p7 <- varSamples %>%
  ggplot(aes(x = area, y = Natural2_slop)) + geom_boxplot() + 
  theme_minimal() + ggtitle("Slope Variance: Natural Reef", subtitle = 
                              "2 x GSD") + 
  ylab("Variance in Slope (degrees)")
# 4xGSD Slope
p8 <- varSamples %>%
  ggplot(aes(x = area, y = Natural4_slop)) + geom_boxplot() + 
  theme_minimal() + ggtitle("Slope Variance: Natural Reef", subtitle = 
                              "4 x GSD") + 
  ylab("Variance in Slope (degrees)")

grid.arrange(p5, p6, p7, p8, ncol = 2)
```






## Analysis

## Surface Relief Ratio (SRR)
```{r, cache = TRUE}
# calculate surface relief ratio
srr_n <- srr(Natural, s = 3)
```

```{r}
# plot srr
plot(srr_n, main = "Surface Relief Ratio, 1xGSD")
```

## 3D Visualization
```{r}
plot3D(Natural)
```

## Contour Plots
```{r}
levelplot(Natural)
```






